version: 1.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform:
- Win32
- Win64

install:
- cmd: premake5.bat

build:
  project: build/DirectXSwapper.sln
  verbosity: minimal

for:
-
  matrix:
    only:
      - platform: Win32
  after_build:
    - cmd: 7z a d3d9.zip %APPVEYOR_BUILD_FOLDER%\data\d3d9.dll
  artifacts:
    - path: d3d9.zip
      name: d3d9
-
  matrix:
    only:
      - platform: Win64
  after_build:
    - cmd: 7z a d3d9_x64.zip %APPVEYOR_BUILD_FOLDER%\data\x64\d3d9.dll
  artifacts:
    - path: d3d9_x64.zip
      name: d3d9_x64

matrix:
  fast_finish: true